decode: prometheus: fix to avoid freeing non-malloced data
fluent/cmetrics pull request #187
Opened 2023-07-24 17:42 UTC by DavidKorczynski

The fuzzer in https://github.com/fluent/fluent-bit/pull/7745 found a bug that shows the prometheus decoder is sometimes freeing data that is not malloced. This is an attempt to fix that.

Please do verify this -- I found the code a bit tricky to validate as I'm not deeply familiar with this decoder.

2023-08-08 18:10 UTC, leonardo-albertovich requested changes

2023-08-08 18:10 UTC, leonardo-albertovich commented on src/cmt_decode_prometheus.c
> +        *name = strdup(*ns);
Please check this result.

2023-08-08 18:10 UTC, leonardo-albertovich commented on src/cmt_decode_prometheus.c
> +        *ns = strdup("");
Please check this result.

2023-08-08 18:10 UTC, leonardo-albertovich commented on src/cmt_decode_prometheus.c
> +            *name = strdup(*subsystem);
Please check this result.

2023-08-08 18:10 UTC, leonardo-albertovich commented on src/cmt_decode_prometheus.c
> +            *name = strdup((*name)++);
Please check this result. and if possible dereference `name` in this way `(*name)[1]`.

2024-02-23 18:40 UTC, edsiper commented
ping @DavidKorczynski on changes requested

2024-02-27 14:09 UTC, DavidKorczynski commented
I think the issue highlighted by this PR may need a more substantial fix. There is mixing of dynamically allocated memory and non-dynamically allocated memory, and in order to achieve consistency there is some rewriting needed (not just fixing). I think the owner/maintainer of the code should address the issues -- @tarruda can you assist here?

2024-03-07 14:10 UTC, edsiper commented
@tarruda it seems this needs a more elaborated solution. would you please take a look at it ? (cc: @niedbalski for visibility)

2026-07-12 17:42 UTC, edsiper commented
This has been refreshed in #287. The new PR preserves @DavidKorczynski’s original signed-off commit, then replaces the mixed-ownership approach with one explicit metric-name buffer owner and adds ASan/UBSan/Valgrind-backed regression tests.

2026-07-12 17:46 UTC, edsiper commented
handled in https://github.com/fluent/cmetrics/pull/287

2026-07-12 17:46 UTC, closed without merging